name=UM SeriesD Helper
version=2.0.0
author=UnexpectedMaker
maintainer=UnexpectedMaker
sentence=Helper library for Unexpected Maker Series[D] boards
paragraph=Currently supports TinyS3[D], ProS3[D], FeatherS3[D], EdgeS3[D], TinyPICO[D] & TinyC6[D]
category=Other
url=https://github.com/UnexpectedMaker/seriesd_arduino_helper
architectures=esp32
includes=UMSeriesD.h